# Generated by Django 3.2 on 2022-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0014_historicalstudent_historicalproject_historicalevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical event'},
        ),
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical project'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical student'},
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
